[versions]
appcompat = "1.7.0"
coilCompose = "2.5.0"
compose_activity = "1.9.0"
compose_nav = "2.7.7"
compose_ui = "1.5.1"
compose_compiler = "1.4.3"
espressoCore = "3.6.1"
gradle = "8.5.1"
hilt = "2.51.1"
hilt_nav_compose = "1.2.0"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlinGradlePlugin = "1.8.10"
ktx = "1.13.1"
lifecycle = "2.8.3"
loggingInterceptor = "4.12.0"
material = "1.2.1"
retrofit = "2.9.0"
retrofit2KotlinxSerializationConverter = "1.0.0"
viewmodel_compose_version = "2.8.3"


[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "compose_activity" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
compose-material3-android = { module = "androidx.compose.material3:material3-android", version.ref = "material" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose_ui" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose_ui" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "ktx" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt_nav_compose" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "compose_nav" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }

[plugins]

[bundles]